#!/usr/bin/perl


use strict;

use CGI qw(:all);
use GD;
use GD::Graph::bars;



#print header();
binmode STDOUT;

my @lines = param('vals');

my @data;
my $tmp;
my $max = 0;
my $min = 0;
my $width = 600;
my $height = 200;


if(param('width'))
{
	$width = param('width');
}
if(param('height'))
{
	$height = param('height');
}

my $x_vals;
my $y_vals;

foreach my $vals(@lines)
{
	my ($x, $y) = split(":", $vals);
	push(@{$x_vals}, $x);
	push(@{$y_vals}, $y);
}

push(@data, $x_vals);
push(@data, $y_vals);

my $graph = GD::Graph::bars->new( 400, 150 );

my $x_label_skip = 25;
my $x_labels_vertical = 1;
my $y_label_skip = 1;
my $y_tick_number = 1;
my $x_label = '';
my $y_label = '';
my $title = '';


if(param('x_label'))
{
	$x_label = param('x_label');
}

if(param('y_label'))
{
	$y_label = param('y_label');
}

if(param('title'))
{
        $title = param('title');
}

if(param('x_label_skip'))
{
        $x_label_skip = param('x_label_skip');
}

if(param('x_labels_vertical'))
{
        $x_labels_vertical = param('x_labels_vertical');
}

if(param('y_label_skip'))
{
        $y_label_skip = param('y_label_skip');
}

if(param('y_tick_number'))
{
        $y_tick_number = param('y_tick_number');
}

$graph->set( 
      x_label           => $x_label,
      y_label           => $y_label,
      title             => $title,
      y_tick_number     => $y_tick_number,
      y_label_skip      => $y_label_skip,
      x_label_skip      => $x_label_skip,
      x_labels_vertical => $x_labels_vertical,
      x_label_position	=>.5,
      box_axis		=>0,
  );
$graph->set( dclrs => [ qw(blue) ] );


print header( -type => "image/png", -expires => "-1d" );
my $gd = $graph->plot(\@data);



print $gd->png;

